### ISSUE TITLE
好像没有重写 Front-matter 中的时间啊

### ISSUE THREAD

**Issue by NanerLee** [xcatliu/hexo-filter-date-from-git#1]
我安装了插件之后, 初始化仓库, add , commit 发现md文件的Front-matter部分并没有改变啊

**Comment by xcatliu** [comment]
md 文件中的 front-matter 会覆盖 git 中读取的

**Comment by xcatliu** [comment]
这个插件不会修改 md 文件，而是覆盖了 page.date （参考 https://hexo.io/zh-cn/docs/variables.html）

**Comment by NanerLee** [comment]
@xcatliu 是我理解错了, 我还以为是会通过修改md文件的, 那这样的话, 如果我手动设置date和updated, 生成的时间就会按照手动设置的来? 如果没有设置或者为空, 就会按照git commit的时间来?

**Comment by xcatliu** [comment]
总结来讲，可以理解为以下情况：

- 如果在 front-matter 中设置了 date，并且早于 git commit 的 date，则以 front-matter 中的为准
- 如果在 front-matter 中设置了 date，并且晚于 git commit 的 date，则以 git commit 中的为准
- 如果没有在 front-matter 中设置 date，则以 git commit 中的为准

---

我本来是想按照你说的那样去设计的。可是 hexo 的 filter 中无法知道 date 是否在 front-matter 中被设置了。

事实上，有四种 date：

1. 文件系统中的 date（不准确，如果是刚 clone 的仓库，则为 clone 的时间）
2. front-matter 中的 date
3. hexo 的 filter 传入的 date——获取自 1 与 2：若没有 front-matter，则读取文件系统中的 date
4. git 中第一次 commit 的 date

由于我的代码中只能获得 3，无法得知它来自于 1 还是 2。所以我只能通过判断 3 与 4 谁先谁后了。

如果 3 早于 4，则说明 3 很有可能是获取自 front-matter 中的 date（因为一般来讲 4 会早于 1），那么我们就使用 3。

反之，我们就需要使用 4 覆盖掉 3 了。

可以看看源码，也只有十几行：
https://github.com/xcatliu/hexo-filter-date-from-git/blob/master/index.js#L12

**Comment by NanerLee** [comment]
恩恩, 谢谢了,讲的很明白

**Comment by yqs112358** [comment]
刚刚也发现了这个问题，跑了一些测试，发现目前传进来`data.date`的行为似乎已经改变过了。具体而言：
1. 如果`front-matter`中设置了date，则`data.date`正常获取；如果未设置，则`data.date`会返回1970-01-01
2. 如果`front-matter`中设置了updated，则`data.updated`正常获取；如果未设置，默认会获取文件系统的文件修改时间mtime作为`data.updated`（这个显然没法用）
3. 但是`_config.yaml`中有个设置项`updated_option`可以改变hexo计算默认`data.updated`的行为，当将其设置为`date`时，hexo会把`data.updated`默认设定为和`data.date`一样的值，即1970-01-01

因此目前只要设置`updated_option: date`，代码中就可以判定`front-matter`中是否有手动填写的日期条目了

**Comment by yqs112358** [comment]
https://github.com/xcatliu/hexo-filter-date-from-git/pull/4
这个PR实现了用hexo-front-matter解析front-matter判断date和updated是否存在，仅不存在时才apply git date🥰

**Comment by xcatliu** [comment]
> #4 这个PR实现了用hexo-front-matter解析front-matter判断date和updated是否存在，仅不存在时才apply git date🥰

published as hexo-filter-date-from-gitv0.2.0 https://www.npmjs.com/package/hexo-filter-date-from-git?activeTab=versions
